<a href="https://colab.research.google.com/github/jurabekkholiqov/Kholikov_01s/blob/main/%2205_ml_09_multiplelr_amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum

## 5-MODUL. Machine Learning.

### Linear Regression

# Multiple Linear Regression

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_LR.csv', index_col=0)
df.head(10)

        district  rooms  size  level  max_levels    price
0   Юнусабадский      3  57.0      4           4  52000.0
1  Яккасарайский      2  52.0      4           5  56000.0
2   Чиланзарский      2  42.0      4           4  37000.0
3   Чиланзарский      3  65.0      1           4  49500.0
4   Чиланзарский      3  70.0      3           5  55000.0
5   Чиланзарский      1  28.0      1           4  25500.0
6   Чиланзарский      1  30.0      2           4  21200.0
7  Яккасарайский      2  32.0      5           5  20000.0
8    Учтепинский      2  51.0      3           4  26200.0
9   Чиланзарский      1  30.0      1           4  22200.0

In [5]:
housing = df[df.district=='Юнусабадский']
housing.head()

        district  rooms  size  level  max_levels    price
0   Юнусабадский      3  57.0      4           4  52000.0
44  Юнусабадский      3  70.0      3           4  47000.0
72  Юнусабадский      2  40.0      1           9  40000.0
74  Юнусабадский      2  53.0      1           9  68000.0
77  Юнусабадский      4  82.0      1           4  86000.0

In [8]:
housing.shape

(847, 6)

In [9]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(housing, test_size=0.1, random_state=42)

In [24]:
from sklearn import linear_model
MLR_model = linear_model.LinearRegression()
x_train = np.asanyarray(train_set[['rooms','size','level','max_levels']])
y_train = np.asanyarray(train_set[['price']])
MLR_model.fit(x_train,y_train)

LinearRegression()

In [25]:
print('Coefficients: ', MLR_model.coef_)
print('theta0:', MLR_model.intercept_)

Coefficients:  [[-2052.50488204   850.34606484 -1596.00179707   394.44229476]]
theta0: [3613.63105765]

In [26]:
x_test = np.asanyarray(test_set[['rooms','size','level','max_levels']])
y_test = np.asanyarray(test_set[['price']])
y_predict = MLR_model.predict(x_test)

In [27]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
MAE = mean_absolute_error(y_test, y_predict)
RMSE = np.sqrt(mean_squared_error(y_test, y_predict))

In [29]:
print(f"{MAE=}")
print(f"{RMSE=}")

MAE=12604.065586004608
RMSE=np.float64(17224.333011685943)